SSH_USERNAME="<ssh_username>"
HOSTING_CONTAINER_NAME="my_content_server"
HOSTING_MACHINE_IP="192.169.0.0"
DOCKER_RESTART_COMMAND='sudo docker restart '+$HOSTING_CONTAINER_NAME

ssh -i $SSH_KEY $SSH_USERNAME@$HOSTING_MACHINE_IP $DOCKER_RESTART_COMMAND